# -*- coding: utf-8 -*-
"""cnn(vit).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17IegmB_7Hb2DIVb85lrfM6Syiwo3seYR
"""

import torch
import torch.nn as nn
import torch.optim as optim

from torchvision import datasets
from torchvision import transforms
from torch.utils.data import DataLoader, random_split

import timm

import matplotlib.pyplot as plt

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print(device)

transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(10),
    transforms.ToTensor()
])

from google.colab import drive
drive.mount('/content/drive')

data_dir="/content/drive/MyDrive/Colab Notebooks/Linear_Nerual_Network/dataset/images"

dataset = datasets.ImageFolder(
    root=data_dir,
    transform=transform
)

print(dataset.classes)
print(len(dataset))

train_size = int(0.8 * len(dataset))

val_size = len(dataset) - train_size

train_dataset, val_dataset = random_split(
    dataset,
    [train_size, val_size]
)

train_loader = DataLoader(
    train_dataset,
    batch_size=32,
    shuffle=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=32,
    shuffle=False
)

model = timm.create_model(
    "vit_base_patch16_224",
    pretrained=True
)

model.head = nn.Linear(
    model.head.in_features,
    9
)

model = model.to(device)

criterion = nn.CrossEntropyLoss()

optimizer = optim.Adam(
    model.parameters(),
    lr=0.0001
)

num_epochs = 20

train_loss_history = []
train_acc_history = []

for epoch in range(num_epochs):

    model.train()

    running_loss = 0

    correct = 0
    total = 0

    for images, labels in train_loader:

        images = images.to(device)
        labels = labels.to(device)

        optimizer.zero_grad()

        outputs = model(images)

        loss = criterion(outputs, labels)

        loss.backward()

        optimizer.step()

        running_loss += loss.item()

        _, predicted = torch.max(outputs,1)

        total += labels.size(0)

        correct += (predicted==labels).sum().item()

    epoch_loss = running_loss/len(train_loader)

    epoch_acc = 100*correct/total

    train_loss_history.append(epoch_loss)

    train_acc_history.append(epoch_acc)

    print(
        f"Epoch {epoch+1}/{num_epochs} "
        f"Loss:{epoch_loss:.4f} "
        f"Accuracy:{epoch_acc:.2f}%"
    )

model.eval()

correct = 0

total = 0

with torch.no_grad():

    for images, labels in val_loader:

        images = images.to(device)

        labels = labels.to(device)

        outputs = model(images)

        _, predicted = torch.max(outputs,1)

        total += labels.size(0)

        correct += (predicted==labels).sum().item()

validation_accuracy = 100*correct/total

print("Validation Accuracy:",validation_accuracy)

plt.figure(figsize=(8,5))

plt.plot(train_loss_history)

plt.title("Training Loss")

plt.xlabel("Epoch")

plt.ylabel("Loss")

plt.show()

plt.figure(figsize=(8,5))

plt.plot(train_acc_history)

plt.title("Training Accuracy")

plt.xlabel("Epoch")

plt.ylabel("Accuracy")

plt.show()

classes = dataset.classes

model.eval()

images, labels = next(iter(val_loader))

images = images.to(device)

with torch.no_grad():

    outputs = model(images)

_, predicted = torch.max(outputs,1)

images = images.cpu()

plt.figure(figsize=(15,10))

for i in range(8):

    plt.subplot(2,4,i+1)

    img = images[i].permute(1,2,0)

    plt.imshow(img)

    plt.title(
        f"Pred:{classes[predicted[i]]}\nActual:{classes[labels[i]]}"
    )

    plt.axis("off")

plt.show()

torch.save(
    model.state_dict(),
    "vit_fruit_classifier.pth"
)

print("Model Saved Successfully")